<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ApplicationManifest>app.manifest</ApplicationManifest>
		<PublishAot Condition="'$(Configuration)' == 'Release'">true</PublishAot>
		 </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\GpuiNetShell\GpuiNetShell.csproj" />
        <ProjectReference Include="..\..\src\GpuiNetShell.SourceGen\GpuiNetShell.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>
